# Server configurations
server:
  port: 8070

# JPA/DB configurations
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:dcbapp
    driverClassName: org.h2.Driver
    username: sa
    password: password


